# Generated by Django 4.0.7 on 2023-10-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_baseuser_created_at_alter_baseuser_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
    ]
