# Generated by Django 4.0.7 on 2023-11-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_baseuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='position',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='position'),
        ),
    ]
