# Generated by Django 4.0.7 on 2023-11-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_baseuser_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='updated_at',
        ),
    ]
