# Generated by Django 4.0.7 on 2023-11-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_baseuser_created_at_baseuser_updated_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='baseuser',
            index=models.Index(fields=['email'], name='users_baseu_email_97cf3e_idx'),
        ),
    ]
