# Generated by Django 4.0.7 on 2023-12-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_public_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='public_name',
        ),
    ]
