# Generated by Django 4.0.7 on 2023-12-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_profile_public_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='public_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='public name'),
        ),
    ]
