# Generated by Django 4.0.7 on 2023-12-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_public_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='public name'),
        ),
    ]
