# Generated by Django 4.0.7 on 2023-10-24 06:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('25abbe5d-31ee-421f-9212-c0113dec3133'), editable=False, primary_key=True, serialize=False),
        ),
    ]
