# Generated by Django 4.0.7 on 2023-10-24 06:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_alter_ingredient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('094cdabf-079f-4674-8119-b8047632b4f9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
