# Generated by Django 4.0.7 on 2023-10-24 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_alter_ingredient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2881f7a5-d42a-43c3-b8e1-8c8e8d94d896'), editable=False, primary_key=True, serialize=False),
        ),
    ]
