# Generated by Django 4.0.7 on 2023-10-24 14:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_alter_ingredient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('image_url', models.CharField(max_length=512, verbose_name='image url')),
                ('image_alt_text', models.CharField(max_length=50, verbose_name='image alt text')),
                ('id', models.UUIDField(default=uuid.UUID('4297d51a-93ab-4a2c-b65a-12fd5c4696fc'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Ingredient Category',
                'verbose_name_plural': 'Ingredient Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='image_alt_text',
            field=models.CharField(default='a', max_length=50, verbose_name='image alt text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='image_url',
            field=models.CharField(default='a', max_length=512, verbose_name='image url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='png_file_alt_text',
            field=models.CharField(default='d', max_length=50, verbose_name='png file alt text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='png_file_url',
            field=models.CharField(default='s', max_length=512, verbose_name='png file url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(default=1, verbose_name='price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='remaining_units',
            field=models.PositiveIntegerField(default=0, verbose_name='remaining units'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default='s', max_length=30, verbose_name='unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a8f1842f-d3db-4ea8-9ef9-294f0e323ac0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='ingredients.ingredientcategory', verbose_name='category'),
            preserve_default=False,
        ),
    ]
