# Generated by Django 4.0.7 on 2023-10-24 14:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_ingredientcategory_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3d488fce-477e-43ef-ab93-379e218c3178'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredientcategory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('284f5c53-8b1c-407c-9769-d893fae999d6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='ingredient',
            table='ingredient',
        ),
        migrations.AlterModelTable(
            name='ingredientcategory',
            table='ingredient_category',
        ),
    ]
