# Generated by Django 4.0.7 on 2023-10-24 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_alter_ingredient_id_alter_ingredientcategory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('19897f0a-e0d8-4513-8f11-2967dd8389d6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredientcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='ingredientcategory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d5890e87-0400-49f6-a72f-ca6dd3c83c58'), editable=False, primary_key=True, serialize=False),
        ),
    ]
