# Generated by Django 4.0.7 on 2023-10-24 16:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0007_alter_ingredient_created_at_alter_ingredient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('658e3593-4544-4d6d-9b9d-2c312a5d4004'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredientcategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
