# Generated by Django 4.0.7 on 2023-11-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0009_alter_ingredient_options_alter_ingredient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='position',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='ingredientcategory',
            name='position',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='position'),
        ),
    ]
