# Generated by Django 4.0.7 on 2023-11-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0010_ingredient_position_ingredientcategory_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('position',), 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='ingredientcategory',
            options={'ordering': ('position',), 'verbose_name': 'Ingredient Category', 'verbose_name_plural': 'Ingredient Categories'},
        ),
    ]
