# Generated by Django 4.0.7 on 2024-01-31 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0012_ingredient_ingredient_categor_e8e8b8_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ingredients', to='ingredients.ingredientcategory', verbose_name='category'),
        ),
    ]
