# Generated by Django 4.0.7 on 2024-02-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0013_alter_ingredient_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='is available'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='stock_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='stock limit'),
        ),
    ]
