# Generated by Django 4.0.7 on 2024-02-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0014_ingredient_is_available_ingredient_stock_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='auto_check_availability',
            field=models.BooleanField(default=False, verbose_name='auto check availability'),
        ),
    ]
