from pizzami.users.documentations.address import CREATE_ADDRESS_RESPONSES
from pizzami.users.documentations.address import DELETE_ADDRESS_RESPONSES
from pizzami.users.documentations.address import GET_ADDRESSES_RESPONSES
from pizzami.users.documentations.address import UPDATE_ADDRESS_RESPONSES
from pizzami.users.documentations.user import GET_USERS_PARAMETERS
from pizzami.users.documentations.user import REQUEST_PASSWORD_RESPONSES
