from pizzami.ingredients.documentation.ingredient_category import GET_INGREDIENT_CATEGORIES_200_RESPONSE
from pizzami.ingredients.documentation.ingredient_category import SAVE_INGREDIENT_CATEGORY_201_RESPONSE
from pizzami.ingredients.documentation.ingredient_category import SAVE_INGREDIENT_CATEGORY_400_RESPONSE
from pizzami.ingredients.documentation.ingredient_category import SAVE_INGREDIENT_CATEGORY_401_RESPONSE
from pizzami.ingredients.documentation.ingredient_category import SAVE_INGREDIENT_CATEGORY_403_RESPONSE
from pizzami.ingredients.documentation.ingredient_category import INGREDIENT_CATEGORY_404_RESPONSE
