# Generated by Django 4.0.7 on 2023-11-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name': 'Food Category', 'verbose_name_plural': 'Food Categories'},
        ),
        migrations.AddField(
            model_name='food',
            name='position',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='position',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='position'),
        ),
    ]
