# Generated by Django 4.0.7 on 2023-11-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_foodcategory_options_food_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'ordering': ('position',), 'verbose_name': 'Food Category', 'verbose_name_plural': 'Food Categories'},
        ),
    ]
