# Generated by Django 4.0.7 on 2023-11-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_foodcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategorycompound',
            options={'ordering': ('position',), 'verbose_name': 'Food Category Compound', 'verbose_name_plural': 'Food Category Compound'},
        ),
        migrations.AddField(
            model_name='foodcategorycompound',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='foodcategorycompound',
            name='position',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='position'),
        ),
    ]
