# Generated by Django 4.0.7 on 2023-11-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_alter_foodcategorycompound_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='foodcategorycompound',
            index=models.Index(fields=['food_category', 'position'], name='food_catego_food_ca_238771_idx'),
        ),
    ]
