# Generated by Django 4.0.7 on 2023-12-22 14:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_public_name'),
        ('foods', '0005_foodcategorycompound_food_catego_food_ca_238771_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('position',), 'verbose_name': 'Food', 'verbose_name_plural': 'Foods'},
        ),
        migrations.AlterModelOptions(
            name='foodcategorycompound',
            options={'ordering': ('position',), 'verbose_name': 'Food Category Compound', 'verbose_name_plural': 'Food Category Compounds'},
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(default='3f44e31e-0db0-4b65-aa45-78f46df51baa', on_delete=django.db.models.deletion.RESTRICT, related_name='foods', to='foods.foodcategory', verbose_name='category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='foods', to='users.profile', verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.TextField(default='dasasdf', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='is confirmed'),
        ),
        migrations.AddField(
            model_name='food',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='is public'),
        ),
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(default='asdfas', max_length=50, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='rate',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='rate'),
        ),
        migrations.AddField(
            model_name='food',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='views'),
        ),
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['category', 'position'], name='food_categor_54d240_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['created_at'], name='food_created_e4d57c_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['rate'], name='food_rate_3f5c03_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['views'], name='food_views_4b0e74_idx'),
        ),
        migrations.AlterModelTable(
            name='food',
            table='food',
        ),
    ]
