# Generated by Django 4.0.7 on 2024-01-21 18:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_public_name'),
        ('ingredients', '0012_ingredient_ingredient_categor_e8e8b8_idx'),
        ('foods', '0006_delete_food_delete_foodingredient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('position', models.PositiveIntegerField(default=0, editable=False, verbose_name='position')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('image_url', models.CharField(max_length=512, verbose_name='image url')),
                ('image_alt_text', models.CharField(max_length=50, verbose_name='image alt text')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('rate', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='rate')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='views')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='is confirmed')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='foods', to='foods.foodcategory', verbose_name='category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='foods', to='users.profile', verbose_name='created by')),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Foods',
                'db_table': 'food',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='FoodIngredient',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('position', models.PositiveIntegerField(default=0, editable=False, verbose_name='position')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='foods.food', verbose_name='food')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='ingredients.ingredient', verbose_name='ingredient')),
            ],
            options={
                'verbose_name': 'FoodIngredient',
                'verbose_name_plural': 'FoodIngredients',
                'db_table': 'food_ingredient',
                'ordering': ('position',),
            },
        ),
        migrations.AddIndex(
            model_name='foodingredient',
            index=models.Index(fields=['food', 'position'], name='food_ingred_food_id_4b45e9_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['category', 'position'], name='food_categor_54d240_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['created_at'], name='food_created_e4d57c_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['rate'], name='food_rate_3f5c03_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['views'], name='food_views_4b0e74_idx'),
        ),
    ]
