# Generated by Django 4.0.7 on 2024-01-21 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_food_foodingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='rate',
            field=models.FloatField(default=0, editable=False, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='food',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='views'),
        ),
    ]
