# Generated by Django 4.0.7 on 2024-01-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_alter_food_rate_alter_food_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.FloatField(default=10.0, verbose_name='price'),
            preserve_default=False,
        ),
    ]
