# Generated by Django 4.0.7 on 2024-01-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_food_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_original',
            field=models.BooleanField(default=True, verbose_name='is original'),
        ),
        migrations.AddField(
            model_name='food',
            name='ordered_count',
            field=models.PositiveIntegerField(default=0, verbose_name='ordered count'),
        ),
        migrations.AlterField(
            model_name='food',
            name='is_confirmed',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='is confirmed'),
        ),
    ]
