# Generated by Django 4.0.7 on 2024-01-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_food_is_original_food_ordered_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='ordered_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='ordered count'),
        ),
    ]
