# Generated by Django 4.0.7 on 2024-01-31 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0013_alter_ingredient_category'),
        ('foods', '0011_alter_food_ordered_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='foods', to='ingredients.ingredient', verbose_name='ingredient'),
        ),
    ]
