# Generated by Django 4.0.7 on 2024-02-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0012_alter_foodingredient_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='is available'),
        ),
    ]
