# Generated by Django 4.0.7 on 2024-02-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0013_food_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='auto_check_availability',
            field=models.BooleanField(default=False, verbose_name='auto check availability'),
        ),
    ]
