# Generated by Django 4.0.7 on 2024-03-08 15:38

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('foods', '0015_food_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='common.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
