# Generated by Django 4.0.7 on 2024-02-20 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_discount_code_alter_discount_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='orders.discount', verbose_name='discount'),
        ),
    ]
