# Generated by Django 4.0.7 on 2024-02-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_value',
            new_name='final_value',
        ),
    ]
