# Generated by Django 4.0.7 on 2024-02-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_total_value_order_final_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_delivery',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='has_delivery'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='address'),
        ),
    ]
