# Generated by Django 4.0.7 on 2024-02-24 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_address_phone_number'),
        ('orders', '0009_remove_order_address_order_address_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.address', verbose_name='address'),
        ),
    ]
