# Generated by Django 4.0.7 on 2024-02-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_str',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='address str'),
        ),
    ]
