# Generated by Django 4.0.7 on 2024-02-24 13:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0015_alter_address_phone_number'),
        ('foods', '0012_alter_foodingredient_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rate')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='foods.food', verbose_name='food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ratings', to='users.profile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'db_table': 'rating',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('position', models.PositiveIntegerField(default=0, editable=False, verbose_name='position')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='text')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='foods.food', verbose_name='food')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='feedback.comment', verbose_name='parent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='users.profile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comment',
                'ordering': ('position',),
            },
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['food'], name='rating_food_id_e45f65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'food')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['food', 'position'], name='comment_food_id_4148b2_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', 'position'], name='comment_user_id_07e79d_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='comment_created_66795a_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['updated_at'], name='comment_updated_cf6917_idx'),
        ),
    ]
